@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjYwNzU5ZmNmLTdmODMtNGQ4Yi1iY2EwLTQ4OTMyOThhZWY1MiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJ2dWFuMjAxIiwianRpIjoiZWIwZTg5ZTQtZDI2Ni00MDhmLTgwYjktYjQzYmFjMzczMDIzIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc2MTY0NTc5OSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzAxNiJ9.BSlvPdOp__7veqWA7gh1GaAarpj46qzYUY5FBJFRkSs
@baseUrl = https://localhost:7016
###
GET {{baseUrl}}/Api/Events
Content-Type: application/json
Authorization: Bearer {{token}}

###